### ISSUE TITLE
Consider @ThreadSafe when importing Java types

### ISSUE THREAD

**Issue by ktoso** [swiftlang/swift-java#129]
While "dormant" some project do use the JSR-305 annotations, and one of them is https://www.javadoc.io/doc/com.google.code.findbugs/jsr305/latest/javax/annotation/concurrent/ThreadSafe.html

This is something we could use to annotate such imported Java types as `Sendable`.

Others are:

Name | Description
-- | --
GuardedBy | The field or method to which this annotation is applied can only be accessed when holding a particular lock, which may be a built-in (synchronization) lock, or may be an explicit Lock.
Immutable | The class to which this annotation is applied is immutable.
NotThreadSafe | The class to which this annotation is applied is not thread-safe.
ThreadSafe | The class to which this annotation is applied is thread-safe.

**Comment by lhoward** [comment]
also see #157
