### ISSUE TITLE
javakit: improve error messages when class missing from classpath

### ISSUE THREAD

**Issue by ktoso** [swiftlang/swift-java#136]
Today it seems we just:

```
Error: org/gradle/tooling/GradleConnector
```

which you can guess what it means but it'll be better if we spell out "Class not found" etc

**Comment by lhoward** [comment]
Also seeing the same thing. Can I assume this means class not found? Do I need to explicitly add the current directory to `classPath` when mapping a class that's defined within a Swift target? Can a single Swift module wrap both classes from an external JAR and those that are located within it?

**Comment by ktoso** [comment]
You'll have to build a "proper" classpath, that's an adventure in of itself but I'm sure we can figure it out.

Most of the time such message is a class not found, but can't guarantee it's just that, that's what this issue is about, making those errors better

**Comment by lhoward** [comment]
OK, so maybe I need to fix this (GH) issue to fix my actual issue :)

Should Swift packages wrapping external JARs be in distinct packages from those that have Java classes (with native methods) inside them?

**Comment by lhoward** [comment]
Can you give me a hint as to where this error message is emitted from? `git grep` offers no hints.

**Comment by ktoso** [comment]
> Should Swift packages wrapping external JARs be in distinct packages from those that have Java classes (with native methods) inside them?

I don't think we have a complete opinion formed here yet. Can you explain in more detail the question. There's various "wrappings" that make sense, for example "a jar that contains java code including native dylib that it calls into (either using JNI or FMM (jextract-swift)" is definitely a thing, mixed language projects eventually too... but this isn't figured out yet. What specifically are you asking about here?

**Comment by ktoso** [comment]
> Can you give me a hint as to where this error message is emitted from? git grep offers no hints.
That's part of this issue I'm afraid 😅 It might be during a `FindClass` call perhaps? Idk if the Java runtime does the print here or who does, we don't seem to have such `Error: ...` print at least.

You could also launch your jvm with `lldb -- java -cp ... <main>` and this way you could maybe find where this happens by stepping through a sample app if nothing else is helping.

**Comment by lhoward** [comment]
> > Should Swift packages wrapping external JARs be in distinct packages from those that have Java classes (with native methods) inside them?
> 
> I don't think we have a complete opinion formed here yet. Can you explain in more detail the question. There's various "wrappings" that make sense, for example "a jar that contains java code including native dylib that it calls into (either using JNI or FMM (jextract-swift)" is definitely a thing, mixed language projects eventually too... but this isn't figured out yet. What specifically are you asking about here?

Ultimately I'm building a shared object to be embedded in an Android APK that will implement some native methods. I'm not asking about the distribution method as much as whether the Swift projections for imported Java API should be in a separate Swift target (module) to Java classes which are embedded in the target. The reason I ask is that it appears that if I don't do this, `Java2Swift.config`'s classPath needs to explicitly refer to  the JavaCompilerPlugin's output directory.

**Comment by lhoward** [comment]
Also, does the classPath in the configuration file augment, or replace the `CLASSPATH` environment variable?

**Comment by ktoso** [comment]
> Also, does the classPath in the configuration file augment, or replace the CLASSPATH environment variable?

AFAICS we don't take into account env variable at all; it's a good question if it should. Probably not, we just need to do a better job at forming classpaths -- right now it's incredibly basic. I have ideas here to form classpaths that include dependencies: https://github.com/swiftlang/swift-java/pull/137

(I really need to rename it to class**p**ath, the uppercase in the Swift word is very weird 😅)

**Comment by ktoso** [comment]
> The reason I ask is that it appears that if I don't do this, Java2Swift.config's classPath appears to need to explicitly refer to the JavaCompilerPlugin's output directory, which seems wrong.

I wholly expect all of this to not be the end state we want to arrive at. Let's start with "what should work" and then work backwards to fix how we form these configurations.

**Comment by ktoso** [comment]
That’s a good idea, yeah. Would you be up for doing a small fix for that?

**Comment by lhoward** [comment]
Are you OK with:

* validating classPath in `JavaVirtualMachine` initializer by checking each element is a valid path (and potentially if it exists?)
* adding a new error type if validation fails

Or would you prefer to not fail but print a warning to stderr?
