### ISSUE TITLE
JavaCompiler: need better way to organise Java dependencies within a package

### ISSUE THREAD

**Issue by lhoward** [swiftlang/swift-java#151]
If I want target B to depend on a Java class compiled by JavaCompilerPlugin in target A, then I need to explicitly set `CLASSPATH` in the environment to point to the build artefacts directory. [1] This should be done by the plugin passing the appropriate argument to `javac`.

[1] which results in other errors but that will be the subject of a separate issue

**Comment by ktoso** [comment]
https://github.com/swiftlang/swift-java/pull/199 a lot of this done here
