### ISSUE TITLE
JavaCompiler:  need flexible argument passing

### ISSUE THREAD

**Issue by lhoward** [swiftlang/swift-java#152]
For example, the Android `javac` defaults to targeting Java SE 21 which isn't compatible with Kotlin. We need to be able to affect the `--target` command line option to `javac` (and by extension other options).

**Comment by ktoso** [comment]
> really I want to pass this as an option to plugin in Package.swift.
>  
> [forums.swift.org/t/swift-package-buildtool-plugin-cannot-accept-arguments-nor-environment-variables/59046](https://forums.swift.org/t/swift-package-buildtool-plugin-cannot-accept-arguments-nor-environment-variables/59046) suggests that it's not possible?

It's a known limitation; we have to work around it with config files, I suggest you add config options to the existing config files.

We'll converge into a single `swiftjava.config` file soon, that would contain config for all the parts.

So for now just add things into the Java2Swift.config

**Comment by lhoward** [comment]
> > really I want to pass this as an option to plugin in Package.swift.
> > [forums.swift.org/t/swift-package-buildtool-plugin-cannot-accept-arguments-nor-environment-variables/59046](https://forums.swift.org/t/swift-package-buildtool-plugin-cannot-accept-arguments-nor-environment-variables/59046) suggests that it's not possible?
> 
> It's a known limitation; we have to work around it with config files, I suggest you add config options to the existing config files.
> 
> We'll converge into a single `swiftjava.config` file soon, that would contain config for all the parts.
> 
> So for now just add things into the Java2Swift.config

OK, this sounds good.

**Comment by lhoward** [comment]
OK with `targetCompatibility` and `sourceCompatibility` keys with integer values?
