### ISSUE TITLE
Create non-optional-returning `as` functions for superclasses/extended interfaces

### ISSUE THREAD

**Issue by DougGregor** [swiftlang/swift-java#20]
`AnyJavaObject` provides [an `as` method](https://github.com/swiftlang/swift-java/blob/main/Sources/JavaKit/JavaObject%2BInheritance.swift#L51) that performs a dynamic cast to another `AnyJavaObject-`conforming type, then returns an optional with either the casted type or `nil` to indicate failure.

When casting to the superclass type or the type of one of the interfaces that a type extends, the result will never be `nil`. Developers performing these upcasts will have to force-unwrap these results. For example:

```swift
let throwable: Throwable = ...
let object: JavaObject = throwable.as(JavaObject.self)!
```

As part of generating the [`Throwable`](https://github.com/swiftlang/swift-java/blob/main/Sources/JavaKit/generated/Throwable.swift) Swift type, we could provide non-optional-returning overloads of `as`, e.g.,

```swift
@JavaClass("java.lang.Throwable")
struct Throwable {
  func as(_: JavaObject.Type) -> JavaObject { ... }
}
```

**Comment by AbdAlRahmanGad** [comment]
Hi @DougGregor,
Could you assign this issue to me?
Could you also point me to which file I should implement this change inside?

**Comment by DougGregor** [comment]
Sure, I've assigned it to you.

I'd expect this change to be implemented in [`JavaClassMacro`](https://github.com/swiftlang/swift-java/blob/main/Sources/JavaKitMacros/JavaClassMacro.swift#L22-L99), because you'll be generating more members inside a type that has `@JavaClass` on it.

New tests can go into [`JavaClassMacroTests`](https://github.com/swiftlang/swift-java/blob/main/Tests/JavaKitMacroTests/JavaClassMacroTests.swift).
