### ISSUE TITLE
Implement Swift wrappers for Java enum types

### ISSUE THREAD

**Issue by DougGregor** [swiftlang/swift-java#21]
Java [enum types](https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html) are encoded as Java classes with various constants for their runtime value. At present, Java2Swift imports these just like any other Java class.

We should try to produce Swift wrappers that either are enums or feel like enums, with support for switches and easy identification of cases.

**Comment by jrosen081** [comment]
Do we have an easy way to get the `JNIEnvironment` statically (instead of as an instance property)? The one thing I've been struggling to design about this is the way I thought of modeling this was one of the following:
1. `static var` on the java struct representation (but the issue is we can't get the `JNIEnvironment` statically I don't think)
2. instance property on `JavaClass` (the issue here is that from my understanding the only way to get the `JavaClass` is to already have an instance of the type, which kind of ruins the point)

**Comment by DougGregor** [comment]
I don't know about "easy". It looks one can get a `JNIEnvironment` for the currently-executing thread using the `JNI_GetCreatedJavaVMs` to get the JavaVM instance and then `GetEnv` to get the `JNIEnvironment`. If that works... actually, if that works, we could possibly drop the `JNIEnvironment` argument to initializers (or make it optional) and use this as a default.

**Comment by DougGregor** [comment]
To follow up on my comments yesterday, it actually wasn't that bad at all to introduce an operation that wraps `GetEnv` to get the JNI environment for the currently-executing thread. The pull request for that step is at https://github.com/swiftlang/swift-java/pull/69.

**Comment by DougGregor** [comment]
I filed away the idea about initializers as https://github.com/swiftlang/swift-java/issues/70

**Comment by jrosen081** [comment]
After playing around with this, enums seem to have their enum cases as static fields, so now that we have #61, we do get these for free (for example here is how `java.lang.annotation.ElementType` gets imported):
```swift
// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("java.lang.annotation.ElementType")
public struct ElementType {
  @JavaMethod
  public func name() -> String

  ... more things from object ...
}
extension JavaClass<ElementType> {
  @JavaStaticField
  public var TYPE: ElementType?

  @JavaStaticField
  public var FIELD: ElementType?

  @JavaStaticField
  public var METHOD: ElementType?

  @JavaStaticField
  public var PARAMETER: ElementType?

  @JavaStaticField
  public var CONSTRUCTOR: ElementType?

  @JavaStaticField
  public var LOCAL_VARIABLE: ElementType?

  @JavaStaticField
  public var ANNOTATION_TYPE: ElementType?

  @JavaStaticField
  public var PACKAGE: ElementType?

  @JavaStaticField
  public var TYPE_PARAMETER: ElementType?

  @JavaStaticField
  public var TYPE_USE: ElementType?

  @JavaStaticField
  public var MODULE: ElementType?

  @JavaStaticField
  public var RECORD_COMPONENT: ElementType?

  @JavaStaticMethod
  public func values() -> [ElementType?]

  @JavaStaticMethod
  public func valueOf(_ arg0: String) -> ElementType?
}
```

(notice that the `RECORD_COMPONENT` is defined [here](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/annotation/ElementType.html#RECORD_COMPONENT) as one of the enum cases). I'm thinking one way to make this a bit nicer would be to make these specific fields non-nullable (and now that we can get the environment we can even create static properties on the base `ElementType` struct in this example). I can put up a pr to add this to make it a bit nicer to use
