### ISSUE TITLE
Generate `@JavaField` in Swift for the public fields of a Java class

### ISSUE THREAD

**Issue by DougGregor** [swiftlang/swift-java#22]
When generating Swift wrappers for Java classes (`Java2Swift` direction), we currently ignore the fields. Instead, we should generate `@JavaField` members so that fields can be accessed directly. For example, a Java class like this:

```java
public class MyClass {
  public int value;
}
```

could be generated as:

```swift
@JavaClass("org.mine.MyClass")
struct MyClass {
  @JavaField
  var value: Int32
}
```

**Comment by jrosen081** [comment]
hey, can I pick this one up? I have the repo building and think I can do this one!

**Comment by DougGregor** [comment]
@jrosen081 Yes, that would be great!

**Comment by jrosen081** [comment]
@DougGregor the pr for it is here #55, let me know what the next steps are!
