### ISSUE TITLE
Java2Swift: Consider translating java.util.Optional into Swift.Optional

### ISSUE THREAD

**Issue by DougGregor** [swiftlang/swift-java#92]
[`java.util.Optional`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html) is very similar in spirit to Swift optionals. We should determine whether there is a good way to automatically translate `java.util.Optional<T>` to `T?` in Swift, correctly.

**Comment by ktoso** [comment]
Note to contributors: watch out for OptionalInt, OptionalLong, OptionalDouble on the java side
